a = input ( 'Введите номер: ' )
b = input ( 'Теперь введите другой номер: ' )
sum = a + b
print ( '\nРезультат сложения двух переменных в sum: ' , sum , type ( sum ) )
sum = int ( a ) + int ( b )
print ( '\nРезультат сложения двух переменных, преобр. в числа в sum: ' , sum , type ( sum ) )
sum = float ( sum )
print ( '\nРезультат сложения двух переменных, преобр. в числа с точкой в sum: ' , sum , type ( sum ) )
sum = chr ( int ( sum ) )
print ( '\nРезультат сложения двух переменных, преобр. в символы в sum: ' , sum , type ( sum ) )
